#!/bin/bash

display_usage() {
	echo "Please ensure device id is added (eg: sda)"
	echo "Usage: bb [device]"
}

if [ $# -le 0 ]
then
	display_usage
	exit 1
fi

clear

echo 'Running test on /dev/'$1

echo -n 'SERIAL ID: ' && udevadm info --query=property --name=/dev/$1 | grep ID_SERIAL | cut -d '=' -f2 | head -1

badblocks -nsv -b 4096 -c 4096 /dev/$1
