#!/bin/bash

display_usage() {
	echo "Please ensure your username and key is set"
	echo "Usage: pull [project name]"
}

username=jazerbarclay
token=`cat $HOME/.keys/git_api_key`
projectslocation=~/projects

if [ $# -le 0 ]
then
	display_usage
	exit 1
fi

projectname=$(echo $@ | tr " " - | tr '[:upper:]' '[:lower:]')
echo "Creating project: $projectname"

pushd $projectslocation && git clone git@github.com:$username/${projectname}.git && popd